version: '3'

volumes:
  pg_data:

services:
  db: 
    image: postgres:13
    container_name: exchange_db
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: .
    container_name: exchange_app
    restart: always
    env_file: .env
    depends_on:
      - db
