openapi: "3.0.2"
info:
  title: Currency Exchange
  description: Simple yet robust currency exchange
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  # /test:
  #   get:
  #     responses:
  #       "200":
  #         description: OK
  /orders:
    get:
      tags: [Orders]
      operationId: getAllOrders
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
    post:
      tags: [Orders]
      operationId: addOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "201":
          description: Created

  /order/{orderId}:
    get:
      tags: [Orders]
      operationId: getOrderById
      parameters:
        - name: orderId
          in: path
          required: true
          description: Unique identifier of the order
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "404":
          description: Order not found

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    OrderType:
      type: string
      enum: [buy, sell]

    Decimal:
      type: string
      format: decimal

    Order:
      type: object
      required: [user_id, order_type, price, amount_initial]
      properties:
        id:
          type: integer
        user_id:
          type: integer
        order_type:
          $ref: "#/components/schemas/OrderType"
        price:
          $ref: "#/components/schemas/Decimal"
        amount_initial:
          $ref: "#/components/schemas/Decimal"
        amount_left:
          $ref: "#/components/schemas/Decimal"
        min_op_threshold:
          $ref: "#/components/schemas/Decimal"
        lifetime:
          type: integer
        creation_time:
          type: integer
