name: Telegram notification on repo update (push)

on:
  push:

jobs:
  send_message:
    name: Send message to Telegram Bot about repo update
    runs-on: ubuntu-latest
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.STATUS_TG_SEND_TO }}
        token: ${{ secrets.STATUS_TG_BOT_TOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
          
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref }}
          
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}